import type { Lang } from '@/lib/appPreferences'

export interface WorkoutScreenStrings {
  /** اسم تمرين فارغ (بلا تمارين). */
  emptyWorkoutNameAr: string
  emptyWorkoutNameEn: string
  /** وسم الإضافة الاختيارية (ذراعان/بطن نهاية اليوم): «(اختياري)» / "(optional)". */
  optionalTag: string
  /** ترويسة الشاشة. */
  workoutEyebrow: string
  workoutHeading: string
  searchLibrary: string
  /** بدء سريع. */
  quickStart: string
  startTodayWorkout: string
  exercisesUnit: string
  startEmptyWorkout: string
  startEmptyDesc: string
  /** خطتي. */
  myPlan: string
  noPlanYet: string
  createMyPlan: string
  daysPerWeek: string
  edit: string
  todayWorkout: string
  noExercises: string
  start: string
  minShort: string
  /** وحدة الثواني المختصرة (ث) للراحة. */
  secShort: string
  /** قوالبي. */
  myTemplates: string
  templatesAutoGenerated: string
  /** إغلاق — زر إغلاق شاشة التمرين. */
  close: string
  /** تم — اعتماد الجولة. */
  done: string
  /** تسمية الجولة المفردة قبل رقمها: «الجولة 1» / "Set 1" (المفاتيح الجمعية في config/strings تبقى للاستخدامات الجمعية). */
  setSingular: string
  /** إرشادات — العناوين. */
  guidanceSummary: string
  techniquePoints: string
  commonMistakes: string
  safetyNote: string
  /** (P12) طريقة استخدام الجهاز — قسم قابل للطي في بطاقة التمرين. */
  howToTitle: string
  /** (P12) زر مشاهدة فيديو الشرح (يفتح خارجيًا). */
  watchVideo: string
  /** (P12) بطاقتا البديل — العنوان والتوضيح. */
  altBlockTitle: string
  altBlockNote: string
  /** (P12) تسميات محتوى بطاقتي البديل. */
  altDumbbellLabel: string
  altDumbbellFallbackLabel: string
  altCableLabel: string
  altCableFallbackLabel: string
  altMachineLabel: string
  /** (P12) زر التبديل داخل البطاقة الصغيرة. */
  switchHere: string
}

const ar: WorkoutScreenStrings = {
  emptyWorkoutNameAr: 'تمرين فارغ',
  emptyWorkoutNameEn: 'Empty Workout',
  optionalTag: '(اختياري)',
  workoutEyebrow: 'تمرين',
  workoutHeading: 'تمرين',
  searchLibrary: 'بحث في المكتبة',
  quickStart: 'بدء سريع',
  startTodayWorkout: 'ابدأ تمرين اليوم',
  exercisesUnit: 'تمارين',
  startEmptyWorkout: 'ابدأ تمرين فارغ',
  startEmptyDesc: 'سجّل مجموعاتك بدون جدول مسبق',
  myPlan: 'خطتي',
  noPlanYet: 'ما عندك جدول حالي — قِمّة تولّد لك خطة من بياناتك وهدفك.',
  createMyPlan: 'أنشئ خطتي',
  daysPerWeek: 'أيام/أسبوع',
  edit: 'تعديل',
  todayWorkout: 'تمرين اليوم',
  noExercises: 'لا تمارين',
  start: 'ابدأ',
  minShort: 'د',
  secShort: 'ث',
  myTemplates: 'قوالبي',
  templatesAutoGenerated: 'خطتك تُولَّد تلقائيًا من بياناتك. عدّل بياناتك من الإعداد لإعادة توليد جدول يناسبك.',
  close: 'إغلاق',
  done: 'تم',
  setSingular: 'الجولة',
  guidanceSummary: 'نقاط التكنيك · أخطاء شائعة · تنبيه أمان',
  techniquePoints: 'نقاط التكنيك',
  commonMistakes: 'أخطاء شائعة',
  safetyNote: 'تنبيه أمان',
  howToTitle: 'طريقة استخدام الجهاز',
  watchVideo: 'شاهد الطريقة',
  altBlockTitle: 'البديل إذا الجهاز غير متوفر',
  altBlockNote: 'التبديل لهذه الجلسة فقط — خطتك تبقى كما هي.',
  altDumbbellLabel: 'بديل دمبل',
  altDumbbellFallbackLabel: 'بديل حر (وزن الجسم)',
  altCableLabel: 'بديل كيبل',
  altCableFallbackLabel: 'بديل بوزن الجسم/دمبل',
  altMachineLabel: 'الجهاز الأساسي',
  switchHere: 'بدّل إليه',
}

const en: WorkoutScreenStrings = {
  emptyWorkoutNameAr: 'تمرين فارغ',
  emptyWorkoutNameEn: 'Empty Workout',
  optionalTag: '(optional)',
  workoutEyebrow: 'Workout',
  workoutHeading: 'Workout',
  searchLibrary: 'Search the library',
  quickStart: 'Quick start',
  startTodayWorkout: "Start today's workout",
  exercisesUnit: 'exercises',
  startEmptyWorkout: 'Start an empty workout',
  startEmptyDesc: 'Log your sets without a preset plan',
  myPlan: 'My plan',
  noPlanYet: "You don't have a plan yet — Qimmah builds one from your data and goal.",
  createMyPlan: 'Build my plan',
  daysPerWeek: 'days/week',
  edit: 'Edit',
  todayWorkout: "Today's workout",
  noExercises: 'No exercises',
  start: 'Start',
  minShort: 'min',
  secShort: 's',
  myTemplates: 'My templates',
  templatesAutoGenerated: 'Your plan is generated automatically from your data. Update your data in Setup to regenerate a plan that fits you.',
  close: 'Close',
  done: 'Done',
  setSingular: 'Set',
  guidanceSummary: 'Technique cues · Common mistakes · Safety note',
  techniquePoints: 'Technique cues',
  commonMistakes: 'Common mistakes',
  safetyNote: 'Safety note',
  howToTitle: 'How to use this machine',
  watchVideo: 'Watch video',
  altBlockTitle: "If the machine isn't available",
  altBlockNote: 'Swap applies to this session only — your plan stays unchanged.',
  altDumbbellLabel: 'Dumbbell alternative',
  altDumbbellFallbackLabel: 'Free alternative (bodyweight)',
  altCableLabel: 'Cable alternative',
  altCableFallbackLabel: 'Bodyweight/dumbbell fallback',
  altMachineLabel: 'Primary machine',
  switchHere: 'Switch to this',
}

export const workoutScreenStrings: Record<Lang, WorkoutScreenStrings> = { ar, en }
