import type { Lang } from '@/lib/appPreferences'

export interface WorkoutScreenStrings {
  /** اسم تمرين فارغ (بلا تمارين). */
  emptyWorkoutNameAr: string
  emptyWorkoutNameEn: string
  /** وسم الإضافة الاختيارية (ذراعان/بطن نهاية اليوم): «(اختياري)» / "(optional)". */
  optionalTag: string
  /** ترويسة الشاشة. */
  workoutEyebrow: string
  workoutHeading: string
  searchLibrary: string
  /** بدء سريع. */
  quickStart: string
  startTodayWorkout: string
  exercisesUnit: string
  startEmptyWorkout: string
  startEmptyDesc: string
  /** خطتي. */
  myPlan: string
  noPlanYet: string
  createMyPlan: string
  daysPerWeek: string
  edit: string
  todayWorkout: string
  noExercises: string
  start: string
  minShort: string
  /** وحدة الثواني المختصرة (ث) للراحة. */
  secShort: string
  /** قوالبي. */
  myTemplates: string
  templatesAutoGenerated: string
  /** إغلاق — زر إغلاق شاشة التمرين. */
  close: string
  /** تم — اعتماد الجولة. */
  done: string
  /** تسمية الجولة المفردة قبل رقمها: «الجولة 1» / "Set 1" (المفاتيح الجمعية في config/strings تبقى للاستخدامات الجمعية). */
  setSingular: string
  /** إرشادات — العناوين. */
  guidanceSummary: string
  techniquePoints: string
  commonMistakes: string
  safetyNote: string
  /** (P12) طريقة استخدام الجهاز — قسم قابل للطي في بطاقة التمرين. */
  howToTitle: string
  /** (P12) زر مشاهدة فيديو الشرح (يفتح خارجيًا). */
  watchVideo: string
  /** (P12) بطاقتا البديل — العنوان والتوضيح. */
  altBlockTitle: string
  altBlockNote: string
  /** (P12) تسميات محتوى بطاقتي البديل. */
  altDumbbellLabel: string
  altDumbbellFallbackLabel: string
  altCableLabel: string
  altCableFallbackLabel: string
  altMachineLabel: string
  /** (ح-١) استئناف جلسة تمرين لم تُنهَ. */
  resumeTitle: string
  resumeBody: string
  resumeAction: string
  resumeDiscard: string
  /** (P12) زر التبديل داخل البطاقة الصغيرة. */
  switchHere: string
  /** فشل حفظ التمرين — واجهة صادقة بدل «تم الحفظ» الزائف. */
  saveFailedTitle: string
  /** سبب: مساحة التخزين ممتلئة. */
  saveFailedQuota: string
  /** سبب: التخزين محجوب (تصفّح خاص / منع تخزين المواقع). */
  saveFailedBlocked: string
  /** سبب: خطأ غير معروف أثناء الحفظ. */
  saveFailedGeneric: string
  /** طمأنة: التمرين الجاري لم يُفقد. */
  saveFailedKept: string
  /** زر إعادة محاولة الحفظ. */
  saveRetry: string
}

const ar: WorkoutScreenStrings = {
  emptyWorkoutNameAr: 'تمرين فارغ',
  emptyWorkoutNameEn: 'Empty Workout',
  optionalTag: '(اختياري)',
  workoutEyebrow: 'تمرين',
  workoutHeading: 'تمرين',
  searchLibrary: 'بحث في المكتبة',
  quickStart: 'بدء سريع',
  startTodayWorkout: 'ابدأ تمرين اليوم',
  exercisesUnit: 'تمارين',
  startEmptyWorkout: 'ابدأ تمرين فارغ',
  startEmptyDesc: 'سجّل مجموعاتك بدون جدول مسبق',
  myPlan: 'خطتي',
  noPlanYet: 'ما عندك جدول حالي — قِمّة تولّد لك خطة من بياناتك وهدفك.',
  createMyPlan: 'جهّز خطتي',
  daysPerWeek: 'أيام/أسبوع',
  edit: 'تعديل',
  todayWorkout: 'تمرين اليوم',
  noExercises: 'ما فيه تمارين',
  start: 'ابدأ',
  minShort: 'د',
  secShort: 'ث',
  myTemplates: 'قوالبي',
  templatesAutoGenerated: 'خطتك تتولّد تلقائي من بياناتك. عدّل بياناتك من الإعداد وبنعيد توليد جدول يناسبك.',
  close: 'إغلاق',
  done: 'تم',
  setSingular: 'الجولة',
  guidanceSummary: 'نقاط التكنيك · أخطاء شائعة · تنبيه أمان',
  techniquePoints: 'نقاط التكنيك',
  commonMistakes: 'أخطاء شائعة',
  safetyNote: 'تنبيه أمان',
  howToTitle: 'طريقة استخدام الجهاز',
  watchVideo: 'شوف الطريقة',
  altBlockTitle: 'البديل إذا الجهاز مو متوفر',
  altBlockNote: 'التبديل لهذي الجلسة بس — خطتك تبقى مثل ما هي.',
  altDumbbellLabel: 'بديل دمبل',
  altDumbbellFallbackLabel: 'بديل حر (وزن الجسم)',
  altCableLabel: 'بديل كيبل',
  altCableFallbackLabel: 'بديل بوزن الجسم/دمبل',
  altMachineLabel: 'الجهاز الأساسي',
  switchHere: 'بدّل له',
  saveFailedTitle: 'لم نتمكّن من حفظ التمرين',
  saveFailedQuota: 'مساحة التخزين على جهازك ممتلئة. أفرغ بعض المساحة ثم أعد المحاولة.',
  saveFailedBlocked: 'التخزين محجوب في هذا المتصفّح (تصفّح خاص أو منع حفظ بيانات المواقع). فعّل التخزين ثم أعد المحاولة.',
  saveFailedGeneric: 'حدث خطأ أثناء الحفظ ولم يُسجَّل شيء.',
  saveFailedKept: 'تمرينك ما زال مفتوحًا كما هو — لم تفقد أي مجموعة.',
  saveRetry: 'أعد محاولة الحفظ',
  resumeTitle: 'عندك تمرين لم ينتهِ',
  resumeBody: 'توقّفت في {day}. تكمّل من مكانك أو تبدأ من جديد؟',
  resumeAction: 'أكمل تمريني',
  resumeDiscard: 'ابدأ نظيفًا',
}

const en: WorkoutScreenStrings = {
  emptyWorkoutNameAr: 'تمرين فارغ',
  emptyWorkoutNameEn: 'Empty Workout',
  optionalTag: '(optional)',
  workoutEyebrow: 'Workout',
  workoutHeading: 'Workout',
  searchLibrary: 'Search the library',
  quickStart: 'Quick start',
  startTodayWorkout: "Start today's workout",
  exercisesUnit: 'exercises',
  startEmptyWorkout: 'Start an empty workout',
  startEmptyDesc: 'Log your sets without a preset plan',
  myPlan: 'My plan',
  noPlanYet: "You don't have a plan yet — Qimmah builds one from your data and goal.",
  createMyPlan: 'Build my plan',
  daysPerWeek: 'days/week',
  edit: 'Edit',
  todayWorkout: "Today's workout",
  noExercises: 'No exercises',
  start: 'Start',
  minShort: 'min',
  secShort: 's',
  myTemplates: 'My templates',
  templatesAutoGenerated: "Your plan is built automatically from your data. Update your data in Setup and we'll rebuild a plan that fits you.",
  close: 'Close',
  done: 'Done',
  setSingular: 'Set',
  guidanceSummary: 'Technique cues · Common mistakes · Safety note',
  techniquePoints: 'Technique cues',
  commonMistakes: 'Common mistakes',
  safetyNote: 'Safety note',
  howToTitle: 'How to use this machine',
  watchVideo: 'Watch video',
  altBlockTitle: "If the machine isn't available",
  altBlockNote: 'The swap is just for this session — your plan stays the same.',
  altDumbbellLabel: 'Dumbbell alternative',
  altDumbbellFallbackLabel: 'Free alternative (bodyweight)',
  altCableLabel: 'Cable alternative',
  altCableFallbackLabel: 'Bodyweight/dumbbell fallback',
  altMachineLabel: 'Primary machine',
  resumeTitle: 'You have an unfinished workout',
  resumeBody: 'You stopped at {day}. Pick up where you left off, or start fresh?',
  resumeAction: 'Resume workout',
  resumeDiscard: 'Start fresh',
  switchHere: 'Switch to this',
  saveFailedTitle: "We couldn't save this workout",
  saveFailedQuota: 'Your device storage is full. Free up some space, then try again.',
  saveFailedBlocked: 'Storage is blocked in this browser (private browsing, or site data is turned off). Enable storage, then try again.',
  saveFailedGeneric: 'Something went wrong while saving — nothing was recorded.',
  saveFailedKept: 'Your workout is still open exactly as it was — no set was lost.',
  saveRetry: 'Try saving again',
}

export const workoutScreenStrings: Record<Lang, WorkoutScreenStrings> = { ar, en }
