// البنك — البرمجة المتقدّمة.
//
// ⚠️ **كل سؤال هنا يحمل `levels` مقيّدًا.** ليست زينة: `PERSONALIZATION-SPEC.md`
// §3.2 يقول «لا مصطلحات RIR/RPE/Deload في مسار المبتدئ» — والقيد هنا هو ما
// يجعل تلك الجملة **قابلة للفحص**: الإثبات يجمع كل سؤال يظهر لمبتدئ ويتأكّد
// أن نصّه خالٍ من قائمة المصطلحات المحظورة. تعليقٌ يقول ذلك يشيخ؛ حقلٌ يقوله
// يُفحص.

import { q, opts } from './define'
import { all, eq, oneOf, ne, gte } from '../rules'
import type { ExperienceClass, QuestionDef } from '../types'

/** التصنيفات التي يجوز عرض البرمجة المتقدّمة لها. */
const ADVANCED_LEVELS: readonly ExperienceClass[] = ['intermediate', 'advanced']
/** يشمل المتوسّط المبكر — أسئلة أخفّ. */
const MID_LEVELS: readonly ExperienceClass[] = ['early_intermediate', 'intermediate', 'advanced', 'returning']

export const ADVANCED_QUESTIONS: QuestionDef[] = [
  q({
    id: 'v-control-level',
    key: 'controlLevel',
    category: 'advanced',
    answer: 'single',
    options: opts('guided', 'balanced', 'full_control'),
    levels: MID_LEVELS,
    affects: ['controlLevel', 'planConstraints'],
    priority: 70,
    infoGain: 8,
    followUps: [{ when: eq('answers.controlLevel', 'full_control'), ask: ['v-split-choice', 'v-volume-pref', 'v-progression-style'] }],
  }),
  q({
    id: 'v-split-choice',
    key: 'splitChoice',
    category: 'advanced',
    answer: 'single',
    options: opts('auto', 'full_body', 'upper_lower', 'push_pull_legs', 'bro_split'),
    levels: MID_LEVELS,
    eligible: oneOf('answers.controlLevel', ['balanced', 'full_control']),
    affects: ['split', 'planConstraints'],
    priority: 66,
    infoGain: 8,
  }),
  q({
    id: 'v-volume-pref',
    key: 'volumePref',
    category: 'advanced',
    answer: 'single',
    options: opts('low', 'moderate', 'high'),
    levels: ADVANCED_LEVELS,
    affects: ['volume', 'planConstraints'],
    priority: 62,
    infoGain: 8,
  }),
  q({
    id: 'v-intensity-pref',
    key: 'intensityPref',
    category: 'advanced',
    answer: 'single',
    options: opts('conservative', 'moderate', 'hard'),
    levels: ADVANCED_LEVELS,
    affects: ['intensity', 'planConstraints'],
    priority: 60,
    infoGain: 7,
  }),
  q({
    id: 'v-rir-familiarity',
    key: 'rirFamiliarity',
    category: 'advanced',
    answer: 'single',
    options: opts('no', 'heard', 'use_it'),
    levels: ADVANCED_LEVELS,
    affects: ['intensity', 'progression'],
    priority: 58,
    infoGain: 7,
    followUps: [{ when: eq('answers.rirFamiliarity', 'use_it'), ask: ['v-target-rir'] }],
  }),
  q({
    id: 'v-target-rir',
    key: 'targetRir',
    category: 'advanced',
    answer: 'slider',
    range: { min: 0, max: 4, step: 1 },
    levels: ADVANCED_LEVELS,
    eligible: eq('answers.rirFamiliarity', 'use_it'),
    affects: ['intensity'],
    priority: 52,
    infoGain: 6,
  }),
  q({
    id: 'v-progression-style',
    key: 'progressionStyle',
    category: 'advanced',
    answer: 'single',
    options: opts('auto', 'double_progression', 'linear_load', 'rep_first', 'rpe_based'),
    levels: ADVANCED_LEVELS,
    affects: ['progression', 'planConstraints'],
    priority: 60,
    infoGain: 8,
  }),
  q({
    id: 'v-deload-pref',
    key: 'deloadPref',
    category: 'advanced',
    answer: 'single',
    options: opts('auto', 'every4', 'every6', 'by_feel', 'none'),
    levels: ADVANCED_LEVELS,
    affects: ['progression', 'volume'],
    priority: 48,
    infoGain: 6,
  }),
  q({
    id: 'v-block-length',
    key: 'blockLength',
    category: 'advanced',
    answer: 'single',
    options: opts('4', '6', '8', '12'),
    levels: ADVANCED_LEVELS,
    affects: ['progression', 'planConstraints'],
    priority: 44,
    infoGain: 5,
  }),
  q({
    id: 'v-strength-hypertrophy-bias',
    key: 'strengthHypertrophyBias',
    category: 'advanced',
    answer: 'single',
    options: opts('strength', 'balanced', 'hypertrophy'),
    levels: ADVANCED_LEVELS,
    affects: ['intensity', 'volume', 'planConstraints'],
    priority: 56,
    infoGain: 8,
  }),
  q({
    id: 'v-exercise-rotation',
    key: 'exerciseRotation',
    category: 'advanced',
    answer: 'single',
    options: opts('fixed', 'per_block', 'frequent'),
    levels: ADVANCED_LEVELS,
    affects: ['planConstraints', 'progression'],
    priority: 42,
    infoGain: 5,
  }),
  q({
    id: 'v-specialisation',
    key: 'specialisation',
    category: 'advanced',
    answer: 'single',
    options: opts('none', 'chest', 'back', 'shoulders', 'arms', 'legs', 'glutes'),
    levels: ADVANCED_LEVELS,
    affects: ['musclePriorities', 'volume'],
    priority: 50,
    infoGain: 7,
  }),
  q({
    id: 'v-frequency-per-muscle',
    key: 'frequencyPerMuscle',
    category: 'advanced',
    answer: 'single',
    options: opts('1', '2', '3'),
    levels: ADVANCED_LEVELS,
    affects: ['split', 'volume', 'planConstraints'],
    priority: 46,
    infoGain: 7,
  }),
  q({
    id: 'v-main-lift-focus',
    key: 'mainLiftFocus',
    category: 'advanced',
    answer: 'multi',
    options: opts('squat', 'bench', 'deadlift', 'overhead', 'pullup', 'none'),
    levels: ADVANCED_LEVELS,
    eligible: oneOf('answers.strengthHypertrophyBias', ['strength', 'balanced']),
    affects: ['musclePriorities', 'planConstraints'],
    priority: 44,
    infoGain: 6,
  }),
  q({
    id: 'v-tempo-control',
    key: 'tempoControl',
    category: 'advanced',
    answer: 'single',
    options: opts('no', 'sometimes', 'yes'),
    levels: ADVANCED_LEVELS,
    affects: ['planConstraints', 'intensity'],
    priority: 30,
    infoGain: 4,
  }),
  q({
    id: 'v-set-to-failure',
    key: 'setToFailure',
    category: 'advanced',
    answer: 'single',
    options: opts('never', 'last_set', 'often'),
    levels: ADVANCED_LEVELS,
    affects: ['intensity', 'volume', 'recovery'],
    priority: 40,
    infoGain: 6,
  }),
  q({
    id: 'v-accessory-appetite',
    key: 'accessoryAppetite',
    category: 'advanced',
    answer: 'single',
    options: opts('minimal', 'balanced', 'lots'),
    levels: ADVANCED_LEVELS,
    affects: ['volume', 'planConstraints'],
    priority: 38,
    infoGain: 5,
  }),
  q({
    id: 'v-weekly-set-target',
    key: 'weeklySetTarget',
    category: 'advanced',
    answer: 'single',
    options: opts('8', '12', '16', '20'),
    levels: ADVANCED_LEVELS,
    eligible: eq('answers.controlLevel', 'full_control'),
    affects: ['volume', 'planConstraints'],
    priority: 42,
    infoGain: 7,
  }),
  q({
    id: 'v-cardio-interference',
    key: 'cardioInterferenceCare',
    category: 'advanced',
    answer: 'boolean',
    levels: ADVANCED_LEVELS,
    eligible: oneOf('answers.cardioWilling', ['yes', 'love_it']),
    affects: ['cardio', 'planConstraints'],
    priority: 34,
    infoGain: 5,
  }),
  q({
    id: 'v-autoregulation',
    key: 'autoregulation',
    category: 'advanced',
    answer: 'single',
    options: opts('no', 'light', 'full'),
    levels: ADVANCED_LEVELS,
    eligible: ne('answers.rirFamiliarity', 'no'),
    affects: ['progression', 'intensity'],
    priority: 36,
    infoGain: 6,
  }),
  q({
    id: 'v-warmup-sets',
    key: 'warmupSets',
    category: 'advanced',
    answer: 'single',
    options: opts('auto', 'minimal', 'full_ramp'),
    levels: ADVANCED_LEVELS,
    affects: ['planConstraints'],
    priority: 26,
    infoGain: 4,
  }),
  q({
    id: 'v-training-age-honest',
    key: 'trainingAgeHonest',
    category: 'advanced',
    answer: 'single',
    options: opts('lt1', 'y1_2', 'y2_5', 'gt5'),
    levels: MID_LEVELS,
    eligible: all(gte('answers.age', 18), ne('answers.trainedBefore', 'never')),
    affects: ['experience', 'experienceConfidence', 'volume'],
    priority: 54,
    infoGain: 8,
  }),
  q({
    id: 'v-plan-edit-appetite',
    key: 'planEditAppetite',
    category: 'advanced',
    answer: 'single',
    options: opts('never', 'sometimes', 'often'),
    levels: MID_LEVELS,
    affects: ['controlLevel', 'planConstraints'],
    priority: 32,
    infoGain: 4,
  }),
  q({
    id: 'v-metric-tracking',
    key: 'metricTracking',
    category: 'advanced',
    answer: 'multi',
    options: opts('weight', 'measurements', 'photos', 'lifts', 'steps', 'none'),
    levels: MID_LEVELS,
    affects: ['progression', 'planConstraints'],
    priority: 28,
    infoGain: 4,
  }),
]
