// البنك — الموافقة والأساسيات والخبرة.
//
// ترتيب مقصود لا عرضي: **الموافقة الصحية أولًا** (`s-health-consent`, أولوية
// 100, غير قابلة للتخطّي) ثم الأساسيات ثم الخبرة. الإذن يسبق الجمع لا يليه —
// وهو نفس الترتيب الذي يفرضه `onboardingV2Flow.ts:179` ويحرسه `test:policy`،
// منقولًا هنا كقاعدة بيانات لا كتعليق.
//
// ⚠️ **العمر ٣١ سؤالًا قبل الهدف عمدًا:** حاجز القاصرين (12+) يحتاج العمر
// **قبل** عرض الأهداف المقيَّدة. `derived.isMinor` يُكتب فور الإجابة، وخيارات
// `g-primary` المقيَّدة معلَّقة عليه — فالقاصر لا تُبنى له خيارات `cut`/`bulk`
// أصلًا، لا تُخفى بـCSS.

import { q, opts } from './define'
import { all, eq, gte, lt, ne, oneOf, has, answered } from '../rules'
import { AGE_MIN } from '../constants'
import type { QuestionDef } from '../types'

export const CORE_QUESTIONS: QuestionDef[] = [
  // ═══════════════════ الموافقة الصحية — بوابة، لا سؤال عادي ═══════════════════
  q({
    id: 's-health-consent',
    key: 'healthConsent',
    category: 'safety',
    answer: 'boolean',
    affects: ['safetyFlags'],
    safety: 'screen',
    priority: 100,
    required: true,
    skippable: false,
    infoGain: 10,
  }),

  // ═══════════════════ الأساسيات ═══════════════════
  q({
    id: 'b-age',
    key: 'age',
    category: 'basics',
    answer: 'number',
    range: { min: AGE_MIN, max: 100, unit: 'year' },
    affects: ['age', 'primaryGoal', 'safetyFlags', 'intensity'],
    safety: 'restrict',
    priority: 98,
    required: true,
    skippable: false,
    infoGain: 10,
    followUps: [{ when: gte('answers.age', 55), ask: ['s-older-adult'] }],
  }),
  q({
    id: 'b-sex',
    key: 'sex',
    category: 'basics',
    answer: 'single',
    options: opts('male', 'female'),
    affects: ['sex'],
    priority: 96,
    required: true,
    skippable: false,
    infoGain: 8,
    followUps: [{ when: all(eq('answers.sex', 'female'), gte('answers.age', 16)), ask: ['s-pregnancy'] }],
  }),
  q({
    id: 'b-height',
    key: 'heightCm',
    category: 'basics',
    answer: 'number',
    range: { min: 120, max: 230, unit: 'cm' },
    affects: ['heightCm'],
    priority: 95,
    required: true,
    skippable: false,
    infoGain: 7,
  }),
  q({
    id: 'b-weight',
    key: 'weightKg',
    category: 'basics',
    answer: 'number',
    range: { min: 30, max: 250, unit: 'kg' },
    affects: ['weightKg', 'safetyFlags'],
    safety: 'screen',
    priority: 95,
    required: true,
    skippable: false,
    infoGain: 7,
  }),
  q({
    id: 'b-units',
    key: 'units',
    category: 'basics',
    answer: 'single',
    options: opts('metric', 'imperial'),
    affects: ['units'],
    priority: 40,
    infoGain: 2,
  }),
  q({
    id: 'b-weight-trend',
    key: 'weightTrend',
    category: 'basics',
    answer: 'single',
    options: opts('rising', 'stable', 'falling', 'unknown'),
    affects: ['primaryGoal', 'planConstraints'],
    priority: 62,
    infoGain: 6,
  }),
  q({
    id: 'b-target-weight',
    key: 'targetWeightKg',
    category: 'basics',
    answer: 'number',
    range: { min: 30, max: 250, unit: 'kg' },
    eligible: all(oneOf('answers.primaryGoal', ['cut', 'bulk']), gte('answers.age', 18)),
    affects: ['planConstraints'],
    priority: 60,
    infoGain: 5,
  }),
  q({
    id: 'b-pace',
    key: 'changePace',
    category: 'basics',
    answer: 'single',
    options: opts('gentle', 'steady', 'aggressive'),
    eligible: all(answered('answers.targetWeightKg'), gte('answers.age', 18)),
    affects: ['planConstraints', 'cardio'],
    priority: 55,
    infoGain: 5,
  }),
  q({
    id: 'b-body-shape',
    key: 'bodyShape',
    category: 'basics',
    answer: 'single',
    options: opts('lean', 'average', 'soft', 'large', 'skip'),
    affects: ['planConstraints', 'cardio'],
    priority: 42,
    infoGain: 4,
  }),

  // ═══════════════════ الخبرة — لا تُقاس بسنة العضوية ═══════════════════
  //
  // ثمانية إشارات مستقلّة تدخل `classifyExperience`. الأصل في المواصفة §11:
  // «من عنده اشتراك ٣ سنوات بلا انتظام قد يكون مبتدئًا». فلا سؤال واحد يحسم.
  q({
    id: 'x-trained-before',
    key: 'trainedBefore',
    category: 'experience',
    answer: 'single',
    options: opts('never', 'tried', 'months', 'years'),
    affects: ['experience', 'trainingStatus'],
    priority: 94,
    required: true,
    skippable: false,
    infoGain: 10,
    followUps: [
      { when: ne('answers.trainedBefore', 'never'), ask: ['x-total-duration', 'x-last-trained', 'x-consistency'] },
      { when: eq('answers.trainedBefore', 'never'), ask: ['x-confidence', 'x-guidance-pref'] },
    ],
  }),
  q({
    id: 'x-total-duration',
    key: 'totalMonths',
    category: 'experience',
    answer: 'single',
    options: opts('lt3', 'm3_6', 'm6_12', 'y1_3', 'y3_plus'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['experience'],
    priority: 88,
    infoGain: 8,
  }),
  q({
    id: 'x-last-trained',
    key: 'lastTrained',
    category: 'experience',
    answer: 'single',
    options: opts('now', 'w2', 'm1_3', 'm3_12', 'y1_plus'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['experience', 'trainingStatus', 'volume'],
    priority: 88,
    infoGain: 9,
    followUps: [{ when: oneOf('answers.lastTrained', ['m3_12', 'y1_plus']), ask: ['x-return-reason', 'x-return-ramp'] }],
  }),
  q({
    id: 'x-consistency',
    key: 'consistency',
    category: 'experience',
    answer: 'single',
    options: opts('rare', 'on_off', 'mostly', 'steady'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['experience', 'trainingStatus', 'daysPerWeek'],
    priority: 86,
    infoGain: 9,
  }),
  q({
    id: 'x-exercise-familiarity',
    key: 'exerciseFamiliarity',
    category: 'experience',
    answer: 'single',
    options: opts('none', 'few', 'most', 'all'),
    affects: ['experience', 'planConstraints'],
    priority: 80,
    infoGain: 8,
  }),
  q({
    id: 'x-program-experience',
    key: 'programExperience',
    category: 'experience',
    answer: 'single',
    options: opts('never', 'app_only', 'followed', 'wrote_own'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['experience', 'controlLevel'],
    priority: 78,
    infoGain: 8,
  }),
  q({
    id: 'x-tracking',
    key: 'tracksSets',
    category: 'experience',
    answer: 'single',
    options: opts('never', 'sometimes', 'always'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['experience', 'progression'],
    priority: 72,
    infoGain: 7,
  }),
  q({
    id: 'x-progression-understanding',
    key: 'knowsProgression',
    category: 'experience',
    answer: 'single',
    options: opts('no', 'vaguely', 'yes'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['experience', 'progression'],
    priority: 70,
    infoGain: 7,
  }),
  q({
    id: 'x-confidence',
    key: 'gymConfidence',
    category: 'experience',
    answer: 'slider',
    range: { min: 1, max: 5, step: 1 },
    affects: ['experience', 'controlLevel', 'planConstraints'],
    priority: 66,
    infoGain: 6,
  }),
  q({
    id: 'x-coached',
    key: 'hadCoach',
    category: 'experience',
    answer: 'single',
    options: opts('never', 'past', 'now'),
    eligible: oneOf('answers.totalMonths', ['y1_3', 'y3_plus']),
    affects: ['experience'],
    priority: 46,
    infoGain: 4,
  }),
  q({
    id: 'x-guidance-pref',
    key: 'guidancePref',
    category: 'experience',
    answer: 'single',
    options: opts('hand_hold', 'balanced', 'minimal'),
    affects: ['controlLevel', 'planConstraints'],
    priority: 58,
    infoGain: 6,
  }),
  q({
    id: 'x-return-reason',
    key: 'returnReason',
    category: 'experience',
    answer: 'single',
    options: opts('injury', 'time', 'motivation', 'life', 'other'),
    eligible: oneOf('answers.lastTrained', ['m3_12', 'y1_plus']),
    affects: ['trainingStatus', 'volume', 'planConstraints'],
    priority: 64,
    infoGain: 7,
    followUps: [{ when: eq('answers.returnReason', 'injury'), ask: ['l-has-injury'] }],
  }),
  q({
    id: 'x-return-ramp',
    key: 'returnRamp',
    category: 'experience',
    answer: 'single',
    options: opts('easy', 'normal', 'straight'),
    eligible: oneOf('answers.lastTrained', ['m3_12', 'y1_plus']),
    affects: ['volume', 'intensity', 'planConstraints'],
    priority: 60,
    infoGain: 6,
  }),
  q({
    id: 'x-prev-results',
    key: 'prevResults',
    category: 'experience',
    answer: 'single',
    options: opts('good', 'mixed', 'none', 'never_ran'),
    eligible: oneOf('answers.programExperience', ['followed', 'wrote_own']),
    affects: ['split', 'volume', 'progression'],
    priority: 54,
    infoGain: 6,
  }),
  q({
    id: 'x-selfrated-level',
    key: 'selfLevel',
    category: 'experience',
    answer: 'single',
    options: opts('beginner', 'intermediate', 'advanced'),
    affects: ['experience', 'experienceConfidence'],
    priority: 76,
    infoGain: 7,
  }),
  q({
    id: 'x-technique-check',
    key: 'techniqueCheck',
    category: 'experience',
    answer: 'single',
    options: opts('no_idea', 'basic', 'confident'),
    eligible: has('answers.equipmentList', 'barbell'),
    affects: ['experience', 'planConstraints'],
    priority: 44,
    infoGain: 5,
  }),
  q({
    id: 'x-warmup-habit',
    key: 'warmupHabit',
    category: 'experience',
    answer: 'single',
    options: opts('never', 'sometimes', 'always'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['planConstraints'],
    priority: 32,
    infoGain: 3,
  }),
  q({
    id: 'x-failure-familiarity',
    key: 'failureFamiliarity',
    category: 'experience',
    answer: 'single',
    options: opts('no', 'sometimes', 'yes'),
    eligible: oneOf('answers.selfLevel', ['intermediate', 'advanced']),
    affects: ['intensity', 'progression'],
    priority: 40,
    infoGain: 5,
  }),
  q({
    id: 'x-strength-marker',
    key: 'strengthMarker',
    category: 'experience',
    answer: 'single',
    options: opts('unknown', 'bodyweight_under', 'bodyweight_around', 'bodyweight_over'),
    eligible: all(eq('answers.selfLevel', 'advanced'), lt('answers.age', 60)),
    affects: ['experience', 'volume'],
    priority: 36,
    infoGain: 5,
  }),
  q({
    id: 'x-session-tolerance',
    key: 'sessionTolerance',
    category: 'experience',
    answer: 'single',
    options: opts('short', 'medium', 'long'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['volume', 'planConstraints'],
    priority: 38,
    infoGain: 4,
  }),
  q({
    id: 'x-other-sport-history',
    key: 'otherSportHistory',
    category: 'experience',
    answer: 'single',
    options: opts('none', 'recreational', 'competitive'),
    affects: ['experience', 'planConstraints'],
    priority: 30,
    infoGain: 4,
  }),
]
