// البنك — الأهداف.
//
// ═══ لماذا ستّة خيارات معروضة وثلاث قيم مخزَّنة ═══
// `GoalValue` في الكود ثلاث قيم فقط (`cut` · `maintain` · `bulk`) وتقودها
// الحسابات كلّها. وشجرة الأسئلة المعتمدة (§10-ب, [CTO-15] §2) اعتمدت **مفهوم**
// الأهداف الستّة بلا توسيع النوع. فالحلّ هنا: الخيار المعروض له قيمته الخاصّة،
// و`sets.goalKey` يطويه إلى إحدى الثلاث. المستخدم يرى لغته، والحساب يرى نوعه،
// ولا نوع جديد يُخترع.
//
// ═══ حاجز القاصرين — بنيوي لا بصري ═══
// كل خيار يفتح عجزًا سعريًا أو فائضًا معلَّق بـ`when: age >= 18`. القاصر
// **لا تُبنى له هذه الخيارات أصلًا** — لا معطَّلة ولا مخفيّة. وهذا هو نصّ
// الاختبار السلوكي المطلوب في §7 من شجرة الأسئلة، منقولًا إلى بيانات.

import { q, opts } from './define'
import { all, any, eq, gte, oneOf, ne, answered } from '../rules'
import { ADULT_AGE } from '../constants'
import type { QuestionDef } from '../types'

/** يُعرض للبالغ فقط — كل هدف يفتح اتجاهًا سعريًا. */
const adult = gte('answers.age', ADULT_AGE)

/** يُعرض لمن تجاوز مرحلة المبتدئ — مصطلحات لا تُعرض لمن لا تفيده. */
const notNovice = oneOf('derived.experienceClass', ['early_intermediate', 'intermediate', 'advanced', 'returning'])

export const GOAL_QUESTIONS: QuestionDef[] = [
  q({
    id: 'g-primary',
    key: 'primaryGoalDisplay',
    category: 'goals',
    answer: 'single',
    options: [
      { value: 'fat_loss', when: adult, sets: { goalKey: 'cut' } },
      { value: 'muscle_gain', when: adult, sets: { goalKey: 'bulk' } },
      { value: 'general_health', sets: { goalKey: 'maintain' } },
      { value: 'get_fitter', sets: { goalKey: 'maintain' } },
      { value: 'recomp', when: all(adult, notNovice), sets: { goalKey: 'maintain' } },
      { value: 'strength', when: all(adult, notNovice), sets: { goalKey: 'bulk' } },
    ],
    affects: ['primaryGoal', 'planConstraints', 'volume', 'cardio'],
    priority: 92,
    required: true,
    skippable: false,
    infoGain: 10,
    followUps: [
      { when: oneOf('answers.primaryGoalDisplay', ['fat_loss']), ask: ['g-fatloss-focus', 'b-target-weight', 'g-cardio-willing'] },
      { when: oneOf('answers.primaryGoalDisplay', ['muscle_gain', 'strength']), ask: ['g-gain-focus', 'b-target-weight'] },
      { when: eq('answers.primaryGoalDisplay', 'recomp'), ask: ['g-recomp-bias'] },
      { when: oneOf('answers.primaryGoalDisplay', ['general_health', 'get_fitter']), ask: ['g-health-driver'] },
    ],
  }),
  q({
    id: 'g-secondary',
    key: 'secondaryGoalDisplay',
    category: 'goals',
    answer: 'single',
    options: opts('none', 'fat_loss', 'muscle_gain', 'strength', 'endurance', 'mobility', 'posture'),
    eligible: answered('answers.primaryGoalDisplay'),
    affects: ['secondaryGoal', 'planConstraints'],
    priority: 58,
    infoGain: 6,
  }),
  q({
    id: 'g-fatloss-focus',
    key: 'fatLossFocus',
    category: 'goals',
    answer: 'single',
    options: opts('keep_muscle', 'fastest', 'sustainable'),
    eligible: all(eq('answers.primaryGoalDisplay', 'fat_loss'), adult),
    affects: ['volume', 'cardio', 'planConstraints'],
    priority: 66,
    infoGain: 7,
  }),
  q({
    id: 'g-gain-focus',
    key: 'gainFocus',
    category: 'goals',
    answer: 'single',
    options: opts('size', 'strength', 'both'),
    eligible: all(oneOf('answers.primaryGoalDisplay', ['muscle_gain', 'strength']), adult),
    affects: ['volume', 'intensity', 'planConstraints'],
    priority: 66,
    infoGain: 7,
  }),
  q({
    id: 'g-recomp-bias',
    key: 'recompBias',
    category: 'goals',
    answer: 'single',
    options: opts('lean_first', 'balanced', 'muscle_first'),
    eligible: eq('answers.primaryGoalDisplay', 'recomp'),
    affects: ['volume', 'cardio', 'planConstraints'],
    priority: 60,
    infoGain: 6,
  }),
  q({
    id: 'g-health-driver',
    key: 'healthDriver',
    category: 'goals',
    answer: 'multi',
    options: opts('energy', 'sleep', 'mood', 'blood_markers', 'mobility', 'daily_ease'),
    select: { min: 1, max: 3 },
    eligible: oneOf('answers.primaryGoalDisplay', ['general_health', 'get_fitter']),
    affects: ['planConstraints', 'cardio'],
    priority: 56,
    infoGain: 5,
  }),
  q({
    id: 'g-cardio-willing',
    key: 'cardioWilling',
    category: 'goals',
    answer: 'single',
    options: opts('no', 'little', 'yes', 'love_it'),
    affects: ['cardio', 'planConstraints'],
    priority: 62,
    infoGain: 6,
    followUps: [{ when: oneOf('answers.cardioWilling', ['yes', 'love_it']), ask: ['p-cardio-type'] }],
  }),
  q({
    id: 'g-horizon',
    key: 'goalHorizon',
    category: 'goals',
    answer: 'single',
    options: opts('m1', 'm3', 'm6', 'ongoing'),
    affects: ['planConstraints', 'progression'],
    priority: 50,
    infoGain: 5,
  }),
  q({
    id: 'g-event',
    key: 'hasEvent',
    category: 'goals',
    answer: 'boolean',
    eligible: oneOf('answers.goalHorizon', ['m1', 'm3']),
    affects: ['planConstraints'],
    priority: 34,
    infoGain: 4,
  }),
  q({
    id: 'g-muscle-priority',
    key: 'musclePriority',
    category: 'goals',
    answer: 'multi',
    options: opts('chest', 'back', 'shoulders', 'arms', 'legs', 'glutes', 'core', 'balanced'),
    select: { min: 1, max: 3 },
    eligible: notNovice,
    affects: ['musclePriorities', 'planConstraints'],
    priority: 54,
    infoGain: 7,
  }),
  q({
    id: 'g-weak-point',
    key: 'weakPoint',
    category: 'goals',
    answer: 'single',
    options: opts('none', 'chest', 'back', 'shoulders', 'arms', 'legs', 'glutes', 'core'),
    eligible: oneOf('derived.experienceClass', ['intermediate', 'advanced']),
    affects: ['musclePriorities', 'volume'],
    priority: 44,
    infoGain: 6,
  }),
  q({
    id: 'g-posture-concern',
    key: 'postureConcern',
    category: 'goals',
    answer: 'boolean',
    affects: ['musclePriorities', 'planConstraints'],
    priority: 30,
    infoGain: 4,
  }),
  q({
    id: 'g-mobility-goal',
    key: 'mobilityGoal',
    category: 'goals',
    answer: 'single',
    options: opts('no', 'some', 'priority'),
    affects: ['planConstraints', 'trainingStyle'],
    priority: 32,
    infoGain: 4,
  }),
  q({
    id: 'g-performance-sport',
    key: 'performanceSport',
    category: 'goals',
    answer: 'single',
    options: opts('none', 'football', 'running', 'combat', 'padel', 'swimming', 'other'),
    eligible: ne('answers.otherSportHistory', 'none'),
    affects: ['planConstraints', 'cardio', 'musclePriorities'],
    priority: 38,
    infoGain: 5,
  }),
  q({
    id: 'g-endurance-target',
    key: 'enduranceTarget',
    category: 'goals',
    answer: 'single',
    options: opts('none', 'walk_longer', 'run_5k', 'run_10k', 'stairs'),
    eligible: any(eq('answers.secondaryGoalDisplay', 'endurance'), oneOf('answers.cardioWilling', ['yes', 'love_it'])),
    affects: ['cardio', 'planConstraints'],
    priority: 36,
    infoGain: 5,
  }),
  q({
    id: 'g-motivation-driver',
    key: 'motivationDriver',
    category: 'goals',
    answer: 'single',
    options: opts('look', 'health', 'strength', 'habit', 'competition'),
    affects: ['planConstraints', 'progression'],
    priority: 28,
    infoGain: 4,
  }),
  q({
    id: 'g-past-obstacle',
    key: 'pastObstacle',
    category: 'goals',
    answer: 'single',
    options: opts('time', 'motivation', 'injury', 'confusion', 'travel', 'none'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['planConstraints', 'daysPerWeek'],
    priority: 48,
    infoGain: 6,
  }),
  q({
    id: 'g-success-metric',
    key: 'successMetric',
    category: 'goals',
    answer: 'single',
    options: opts('scale', 'mirror', 'measurements', 'lifts', 'how_i_feel'),
    affects: ['planConstraints', 'progression'],
    priority: 40,
    infoGain: 5,
  }),
  q({
    id: 'g-plan-adherence-style',
    key: 'adherenceStyle',
    category: 'goals',
    answer: 'single',
    options: opts('strict', 'flexible', 'minimal'),
    affects: ['planConstraints', 'controlLevel'],
    priority: 42,
    infoGain: 5,
  }),
  q({
    id: 'g-body-focus-balance',
    key: 'upperLowerBalance',
    category: 'goals',
    answer: 'single',
    options: opts('upper', 'balanced', 'lower'),
    eligible: notNovice,
    affects: ['musclePriorities', 'split'],
    priority: 46,
    infoGain: 6,
  }),
  q({
    id: 'g-plateau',
    key: 'hitPlateau',
    category: 'goals',
    answer: 'boolean',
    eligible: oneOf('derived.experienceClass', ['intermediate', 'advanced']),
    affects: ['progression', 'volume'],
    priority: 40,
    infoGain: 5,
  }),
  q({
    id: 'g-nutrition-interest',
    key: 'nutritionInterest',
    category: 'goals',
    answer: 'single',
    options: opts('numbers_only', 'meal_ideas', 'both', 'skip'),
    affects: ['planConstraints'],
    priority: 44,
    infoGain: 5,
  }),
]
