// البنك — الفرز الآمن والقيود الجسدية.
//
// ═══ حدّ معلَن: هذا فرز، لا تشخيص ═══
// أسئلة `s-*` تسأل عن **أعراض أبلغ عنها المستخدم أو تعليمات قالها له مختصّ**.
// لا تسمّي مرضًا، ولا تستنتجه، ولا تعطي رأيًا طبيًا. مخرجها الوحيد:
// `safety.needsClearance` + قيود استبعاد. أي إجابة تُقلق ⇒ **رسالة تنصح
// بمراجعة مختصّ + تقييد التمارين عالية الخطورة**، والتطبيق يبقى مفتوحًا.
// (المواصفة §3: «نظام تخصيص لياقة، لا نظام تشخيص طبي».)
//
// ═══ ولماذا القيود قائمة مغلقة ═══
// `BODY_AREAS` عشر مناطق مغلقة. نصّ حرّ هنا يعني قيدًا **لا يستطيع المحرّك
// ترجمته إلى استبعاد فعلي** — أي وعد بأمان لا يُنفَّذ. النص الحرّ متاح **بعد**
// الاختيار المغلق كتفصيل يقرأه الإنسان لا الفلتر (`l-notes`).

import { q, opts } from './define'
import { all, any, eq, gte, oneOf, has, hasAny } from '../rules'
import { BODY_AREAS, type QuestionDef } from '../types'

const areaOptions = BODY_AREAS.map((value) => ({ value }))

/** أي إشارة فرز موجبة. */
const anyRedFlag = any(
  eq('answers.chestPain', true),
  eq('answers.fainting', true),
  eq('answers.doctorRestriction', true),
  eq('answers.recentSurgery', true),
  oneOf('answers.pregnancyStatus', ['pregnant', 'postpartum']),
)

export const HEALTH_QUESTIONS: QuestionDef[] = [
  // ═══════════════════ الفرز الآمن ═══════════════════
  q({
    id: 's-screen-gate',
    key: 'screenGate',
    category: 'safety',
    answer: 'boolean',
    affects: ['safetyFlags'],
    safety: 'screen',
    priority: 84,
    required: true,
    skippable: false,
    infoGain: 9,
    followUps: [
      { when: eq('answers.screenGate', true), ask: ['s-chest-pain', 's-fainting', 's-doctor-restriction', 's-recent-surgery'] },
    ],
  }),
  q({
    id: 's-chest-pain',
    key: 'chestPain',
    category: 'safety',
    answer: 'boolean',
    eligible: eq('answers.screenGate', true),
    affects: ['safetyFlags', 'intensity', 'cardio'],
    safety: 'clear',
    priority: 83,
    skippable: false,
    infoGain: 9,
  }),
  q({
    id: 's-fainting',
    key: 'fainting',
    category: 'safety',
    answer: 'boolean',
    eligible: eq('answers.screenGate', true),
    affects: ['safetyFlags', 'intensity'],
    safety: 'clear',
    priority: 83,
    skippable: false,
    infoGain: 8,
  }),
  q({
    id: 's-doctor-restriction',
    key: 'doctorRestriction',
    category: 'safety',
    answer: 'boolean',
    eligible: eq('answers.screenGate', true),
    affects: ['safetyFlags', 'planConstraints'],
    safety: 'clear',
    priority: 83,
    skippable: false,
    infoGain: 9,
    followUps: [{ when: eq('answers.doctorRestriction', true), ask: ['s-restriction-area'] }],
  }),
  q({
    id: 's-restriction-area',
    key: 'restrictionAreas',
    category: 'safety',
    answer: 'bodyAreas',
    options: areaOptions,
    eligible: eq('answers.doctorRestriction', true),
    affects: ['safetyFlags', 'limitations'],
    safety: 'restrict',
    priority: 82,
    infoGain: 9,
  }),
  q({
    id: 's-recent-surgery',
    key: 'recentSurgery',
    category: 'safety',
    answer: 'boolean',
    eligible: eq('answers.screenGate', true),
    affects: ['safetyFlags', 'volume', 'intensity'],
    safety: 'clear',
    priority: 83,
    skippable: false,
    infoGain: 9,
    followUps: [{ when: eq('answers.recentSurgery', true), ask: ['s-surgery-when', 's-surgery-area'] }],
  }),
  q({
    id: 's-surgery-when',
    key: 'surgeryWhen',
    category: 'safety',
    answer: 'single',
    options: opts('under6w', 'w6_12', 'm3_6', 'over6m'),
    eligible: eq('answers.recentSurgery', true),
    affects: ['safetyFlags', 'volume'],
    safety: 'clear',
    priority: 82,
    infoGain: 8,
  }),
  q({
    id: 's-surgery-area',
    key: 'surgeryAreas',
    category: 'safety',
    answer: 'bodyAreas',
    options: areaOptions,
    eligible: eq('answers.recentSurgery', true),
    affects: ['safetyFlags', 'limitations'],
    safety: 'restrict',
    priority: 82,
    infoGain: 8,
  }),
  q({
    id: 's-pregnancy',
    key: 'pregnancyStatus',
    category: 'safety',
    answer: 'single',
    options: opts('no', 'pregnant', 'postpartum', 'prefer_not'),
    eligible: all(eq('answers.sex', 'female'), gte('answers.age', 16)),
    affects: ['safetyFlags', 'intensity', 'planConstraints'],
    safety: 'clear',
    priority: 80,
    infoGain: 8,
  }),
  q({
    id: 's-older-adult',
    key: 'olderAdultCare',
    category: 'safety',
    answer: 'multi',
    options: opts('none', 'balance', 'joints', 'blood_pressure', 'bone_density'),
    eligible: gte('answers.age', 55),
    affects: ['safetyFlags', 'planConstraints', 'intensity'],
    safety: 'restrict',
    priority: 74,
    infoGain: 7,
  }),
  q({
    id: 's-breathing',
    key: 'breathingIssue',
    category: 'safety',
    answer: 'boolean',
    eligible: eq('answers.screenGate', true),
    affects: ['safetyFlags', 'cardio'],
    safety: 'restrict',
    priority: 72,
    infoGain: 6,
  }),
  q({
    id: 's-dizziness-on-effort',
    key: 'dizzinessOnEffort',
    category: 'safety',
    answer: 'boolean',
    eligible: anyRedFlag,
    affects: ['safetyFlags', 'intensity'],
    safety: 'clear',
    priority: 70,
    infoGain: 6,
  }),
  q({
    id: 's-clearance-ack',
    key: 'clearanceAck',
    category: 'safety',
    answer: 'boolean',
    eligible: anyRedFlag,
    affects: ['safetyFlags'],
    safety: 'clear',
    priority: 79,
    skippable: false,
    infoGain: 7,
  }),

  // ═══════════════════ القيود الجسدية ═══════════════════
  q({
    id: 'l-has-injury',
    key: 'hasInjury',
    category: 'limitations',
    answer: 'single',
    options: opts('none', 'past', 'current'),
    affects: ['limitations', 'safetyFlags'],
    safety: 'screen',
    priority: 85,
    required: true,
    skippable: false,
    infoGain: 9,
    followUps: [
      { when: eq('answers.hasInjury', 'current'), ask: ['l-current-areas', 'l-pain-on-movement', 'l-pain-level'] },
      { when: eq('answers.hasInjury', 'past'), ask: ['l-past-areas', 'l-past-recovered'] },
    ],
  }),
  q({
    id: 'l-current-areas',
    key: 'currentInjuryAreas',
    category: 'limitations',
    answer: 'bodyAreas',
    options: areaOptions,
    select: { min: 1 },
    eligible: eq('answers.hasInjury', 'current'),
    affects: ['limitations', 'safetyFlags', 'excludedExercises'],
    safety: 'restrict',
    priority: 84,
    skippable: false,
    infoGain: 10,
    followUps: [
      { when: has('answers.currentInjuryAreas', 'shoulder'), ask: ['l-shoulder-overhead'] },
      { when: has('answers.currentInjuryAreas', 'knee'), ask: ['l-knee-depth'] },
      { when: has('answers.currentInjuryAreas', 'lower_back'), ask: ['l-back-hinge'] },
      { when: has('answers.currentInjuryAreas', 'wrist'), ask: ['l-wrist-grip'] },
    ],
  }),
  q({
    id: 'l-past-areas',
    key: 'pastInjuryAreas',
    category: 'limitations',
    answer: 'bodyAreas',
    options: areaOptions,
    eligible: eq('answers.hasInjury', 'past'),
    affects: ['limitations', 'planConstraints'],
    safety: 'restrict',
    priority: 64,
    infoGain: 7,
  }),
  q({
    id: 'l-past-recovered',
    key: 'pastRecovered',
    category: 'limitations',
    answer: 'single',
    options: opts('fully', 'mostly', 'flares'),
    eligible: eq('answers.hasInjury', 'past'),
    affects: ['limitations', 'safetyFlags'],
    safety: 'restrict',
    priority: 62,
    infoGain: 7,
  }),
  q({
    id: 'l-pain-on-movement',
    key: 'painOnMovement',
    category: 'limitations',
    answer: 'multi',
    options: opts('none', 'push', 'pull', 'squat', 'hinge', 'overhead', 'twist', 'impact'),
    eligible: eq('answers.hasInjury', 'current'),
    affects: ['safetyFlags', 'excludedExercises', 'planConstraints'],
    safety: 'restrict',
    priority: 82,
    infoGain: 10,
  }),
  q({
    id: 'l-pain-level',
    key: 'painLevel',
    category: 'limitations',
    answer: 'slider',
    range: { min: 0, max: 10, step: 1 },
    eligible: eq('answers.hasInjury', 'current'),
    affects: ['safetyFlags', 'intensity', 'volume'],
    safety: 'clear',
    priority: 80,
    infoGain: 8,
  }),
  q({
    id: 'l-shoulder-overhead',
    key: 'shoulderOverhead',
    category: 'limitations',
    answer: 'single',
    options: opts('fine', 'uncomfortable', 'cannot'),
    eligible: hasAny('answers.currentInjuryAreas', ['shoulder']),
    affects: ['safetyFlags', 'excludedExercises'],
    safety: 'restrict',
    priority: 76,
    infoGain: 8,
  }),
  q({
    id: 'l-knee-depth',
    key: 'kneeDepth',
    category: 'limitations',
    answer: 'single',
    options: opts('full', 'partial', 'minimal'),
    eligible: hasAny('answers.currentInjuryAreas', ['knee']),
    affects: ['safetyFlags', 'excludedExercises', 'planConstraints'],
    safety: 'restrict',
    priority: 76,
    infoGain: 8,
  }),
  q({
    id: 'l-back-hinge',
    key: 'backHinge',
    category: 'limitations',
    answer: 'single',
    options: opts('fine', 'light_only', 'avoid'),
    eligible: hasAny('answers.currentInjuryAreas', ['lower_back']),
    affects: ['safetyFlags', 'excludedExercises'],
    safety: 'restrict',
    priority: 76,
    infoGain: 8,
  }),
  q({
    id: 'l-wrist-grip',
    key: 'wristGrip',
    category: 'limitations',
    answer: 'single',
    options: opts('fine', 'straps_needed', 'limited'),
    eligible: hasAny('answers.currentInjuryAreas', ['wrist']),
    affects: ['safetyFlags', 'excludedExercises'],
    safety: 'restrict',
    priority: 66,
    infoGain: 6,
  }),
  q({
    id: 'l-balance',
    key: 'balanceIssue',
    category: 'limitations',
    answer: 'single',
    options: opts('none', 'some', 'significant'),
    eligible: any(gte('answers.age', 55), eq('answers.hasInjury', 'current')),
    affects: ['safetyFlags', 'excludedExercises', 'planConstraints'],
    safety: 'restrict',
    priority: 60,
    infoGain: 7,
  }),
  q({
    id: 'l-rom-limits',
    key: 'romLimits',
    category: 'limitations',
    answer: 'bodyAreas',
    options: areaOptions,
    eligible: oneOf('answers.hasInjury', ['past', 'current']),
    affects: ['limitations', 'planConstraints'],
    safety: 'restrict',
    priority: 54,
    infoGain: 6,
  }),
  q({
    id: 'l-joint-sensitivity',
    key: 'jointSensitivity',
    category: 'limitations',
    answer: 'multi',
    options: opts('none', 'shoulder', 'elbow', 'wrist', 'hip', 'knee', 'ankle'),
    affects: ['limitations', 'planConstraints', 'excludedExercises'],
    safety: 'restrict',
    priority: 52,
    infoGain: 6,
  }),
  q({
    id: 'l-impact-tolerance',
    key: 'impactTolerance',
    category: 'limitations',
    answer: 'single',
    options: opts('fine', 'limited', 'none'),
    affects: ['safetyFlags', 'cardio', 'excludedExercises'],
    safety: 'restrict',
    priority: 56,
    infoGain: 6,
  }),
  q({
    id: 'l-medication-effect',
    key: 'medicationEffect',
    category: 'limitations',
    answer: 'single',
    options: opts('none', 'some', 'prefer_not'),
    eligible: eq('answers.screenGate', true),
    affects: ['safetyFlags', 'intensity'],
    safety: 'restrict',
    priority: 50,
    infoGain: 5,
  }),
  q({
    id: 'l-notes',
    key: 'limitationNotes',
    category: 'limitations',
    answer: 'text',
    eligible: oneOf('answers.hasInjury', ['past', 'current']),
    affects: ['limitations'],
    priority: 18,
    infoGain: 2,
  }),
  q({
    id: 'l-cannot-perform',
    key: 'cannotPerform',
    category: 'limitations',
    answer: 'exercises',
    eligible: oneOf('answers.hasInjury', ['past', 'current']),
    affects: ['excludedExercises', 'planConstraints'],
    safety: 'restrict',
    priority: 58,
    infoGain: 7,
  }),
  q({
    id: 'l-standing-tolerance',
    key: 'standingTolerance',
    category: 'limitations',
    answer: 'single',
    options: opts('fine', 'limited', 'seated_only'),
    eligible: any(gte('answers.age', 60), eq('answers.balanceIssue', 'significant')),
    affects: ['safetyFlags', 'excludedExercises', 'planConstraints'],
    safety: 'restrict',
    priority: 48,
    infoGain: 6,
  }),
  q({
    id: 'l-breath-holding',
    key: 'breathHoldingRisk',
    category: 'limitations',
    answer: 'boolean',
    eligible: any(gte('answers.age', 55), eq('answers.doctorRestriction', true)),
    affects: ['safetyFlags', 'intensity'],
    safety: 'restrict',
    priority: 46,
    infoGain: 5,
  }),
]
