// البنك — التوافر والمكان والمعدّات.
//
// ═══ لماذا المعدّات سؤالٌ مفرَّع لا قائمة واحدة ═══
// مفردات المعدّات في `EQUIPMENT_VOCAB` **مأخوذة حرفيًا من `src/data/exercises.ts`**
// (اثنتا عشرة مفردة، لا مخترَعة). عرضها كلّها على من قال «نادٍ تجاري» عبث: النادي
// يعني توفّرها كلّها افتراضًا. فالقائمة الطويلة تظهر **للمنزل والهواء الطلق فقط**،
// وهو ما يجعل مسار النادي أقصر بسؤالين بلا خسارة معلومة.

import { q, opts } from './define'
import { all, any, eq, gte, oneOf, ne, has, hasAny, hasNone, answered, not } from '../rules'
import { EQUIPMENT_VOCAB, type QuestionDef } from '../types'

const atHome = oneOf('answers.place', ['home', 'outdoor', 'mixed'])

export const LOGISTICS_QUESTIONS: QuestionDef[] = [
  // ═══════════════════ التوافر ═══════════════════
  q({
    id: 'a-days',
    key: 'daysPerWeek',
    category: 'availability',
    answer: 'single',
    options: opts('2', '3', '4', '5', '6'),
    affects: ['daysPerWeek', 'split', 'planConstraints'],
    priority: 90,
    required: true,
    skippable: false,
    infoGain: 10,
    followUps: [{ when: gte('answers.daysPerWeek', 4), ask: ['a-preferred-days'] }],
  }),
  q({
    id: 'a-session-minutes',
    key: 'sessionMinutes',
    category: 'availability',
    answer: 'single',
    options: opts('20', '30', '45', '60', '75', '90'),
    affects: ['sessionMinutes', 'volume', 'planConstraints'],
    priority: 89,
    required: true,
    skippable: false,
    infoGain: 9,
  }),
  q({
    id: 'a-preferred-days',
    key: 'availableDays',
    category: 'availability',
    answer: 'weekdays',
    affects: ['availableDays', 'planConstraints'],
    priority: 52,
    infoGain: 5,
  }),
  q({
    id: 'a-time-of-day',
    key: 'timeOfDay',
    category: 'availability',
    answer: 'single',
    options: opts('early', 'morning', 'afternoon', 'evening', 'late', 'varies'),
    affects: ['planConstraints'],
    priority: 46,
    infoGain: 4,
  }),
  q({
    id: 'a-schedule-flex',
    key: 'scheduleFlex',
    category: 'availability',
    answer: 'single',
    options: opts('fixed', 'somewhat', 'flexible'),
    affects: ['planConstraints', 'split'],
    priority: 44,
    infoGain: 5,
  }),
  q({
    id: 'a-travel',
    key: 'travelFrequency',
    category: 'availability',
    answer: 'single',
    options: opts('never', 'rare', 'monthly', 'weekly'),
    affects: ['planConstraints', 'equipment'],
    priority: 38,
    infoGain: 5,
    followUps: [{ when: oneOf('answers.travelFrequency', ['monthly', 'weekly']), ask: ['e-travel-fallback'] }],
  }),
  q({
    id: 'a-commute',
    key: 'gymCommute',
    category: 'availability',
    answer: 'single',
    options: opts('at_home', 'under10', 'under30', 'over30'),
    eligible: oneOf('answers.place', ['gym', 'mixed']),
    affects: ['daysPerWeek', 'planConstraints'],
    priority: 36,
    infoGain: 4,
  }),
  q({
    id: 'a-busy-season',
    key: 'busySeason',
    category: 'availability',
    answer: 'boolean',
    affects: ['planConstraints'],
    priority: 24,
    infoGain: 3,
  }),
  q({
    id: 'a-min-session',
    key: 'minSessionMinutes',
    category: 'availability',
    answer: 'single',
    options: opts('10', '15', '20', '30'),
    eligible: oneOf('answers.scheduleFlex', ['fixed', 'somewhat']),
    affects: ['planConstraints'],
    priority: 30,
    infoGain: 4,
  }),
  q({
    id: 'a-weekend-different',
    key: 'weekendDifferent',
    category: 'availability',
    answer: 'boolean',
    affects: ['availableDays', 'planConstraints'],
    priority: 26,
    infoGain: 3,
  }),
  q({
    id: 'a-can-add-day',
    key: 'canAddDay',
    category: 'availability',
    answer: 'boolean',
    eligible: oneOf('answers.daysPerWeek', ['2', '3']),
    affects: ['daysPerWeek', 'split'],
    priority: 42,
    infoGain: 5,
  }),
  q({
    id: 'a-rest-day-pref',
    key: 'restDayPref',
    category: 'availability',
    answer: 'single',
    options: opts('spread', 'block', 'no_pref'),
    eligible: gte('answers.daysPerWeek', 4),
    affects: ['split', 'planConstraints'],
    priority: 34,
    infoGain: 4,
  }),
  q({
    id: 'a-ramadan-aware',
    key: 'ramadanAware',
    category: 'availability',
    answer: 'single',
    options: opts('yes', 'no', 'maybe'),
    affects: ['planConstraints'],
    priority: 22,
    infoGain: 3,
  }),
  q({
    id: 'a-heat-sensitivity',
    key: 'heatSensitivity',
    category: 'availability',
    answer: 'single',
    options: opts('fine', 'some', 'avoid'),
    eligible: eq('answers.place', 'outdoor'),
    affects: ['planConstraints', 'cardio'],
    priority: 32,
    infoGain: 4,
  }),

  // ═══════════════════ المكان والمعدّات ═══════════════════
  q({
    id: 'e-place',
    key: 'place',
    category: 'equipment',
    answer: 'single',
    options: opts('gym', 'home', 'outdoor', 'mixed'),
    affects: ['place', 'equipment', 'planConstraints'],
    priority: 91,
    required: true,
    skippable: false,
    infoGain: 10,
    followUps: [
      { when: atHome, ask: ['e-equipment-list', 'e-space'] },
      { when: eq('answers.place', 'gym'), ask: ['e-gym-type', 'e-crowded'] },
    ],
  }),
  q({
    id: 'e-equipment-list',
    key: 'equipmentList',
    category: 'equipment',
    answer: 'equipment',
    options: EQUIPMENT_VOCAB.map((value) => ({ value })),
    select: { min: 1 },
    eligible: atHome,
    affects: ['equipment', 'trainingStyle', 'planConstraints'],
    priority: 87,
    required: true,
    skippable: false,
    infoGain: 10,
    followUps: [
      { when: has('answers.equipmentList', 'dumbbell'), ask: ['e-dumbbell-kind', 'e-dumbbell-max'] },
      { when: has('answers.equipmentList', 'barbell'), ask: ['e-plate-max', 'e-rack'] },
      { when: hasNone('answers.equipmentList', ['dumbbell', 'barbell', 'machine', 'cable']), ask: ['e-bodyweight-only-confirm'] },
    ],
  }),
  q({
    id: 'e-gym-type',
    key: 'gymType',
    category: 'equipment',
    answer: 'single',
    options: opts('full', 'machines_only', 'hotel', 'ladies', 'crossfit'),
    eligible: oneOf('answers.place', ['gym', 'mixed']),
    affects: ['equipment', 'trainingStyle', 'planConstraints'],
    priority: 68,
    infoGain: 7,
  }),
  q({
    id: 'e-crowded',
    key: 'gymCrowded',
    category: 'equipment',
    answer: 'single',
    options: opts('never', 'sometimes', 'always'),
    eligible: oneOf('answers.place', ['gym', 'mixed']),
    affects: ['planConstraints'],
    priority: 34,
    infoGain: 4,
  }),
  q({
    id: 'e-dumbbell-kind',
    key: 'dumbbellKind',
    category: 'equipment',
    answer: 'single',
    options: opts('fixed_pair', 'adjustable', 'set'),
    eligible: has('answers.equipmentList', 'dumbbell'),
    affects: ['equipment', 'progression', 'planConstraints'],
    priority: 56,
    infoGain: 6,
  }),
  q({
    id: 'e-dumbbell-max',
    key: 'dumbbellMaxKg',
    category: 'equipment',
    answer: 'number',
    range: { min: 2, max: 60, unit: 'kg' },
    eligible: has('answers.equipmentList', 'dumbbell'),
    affects: ['equipment', 'progression', 'planConstraints'],
    priority: 54,
    infoGain: 6,
  }),
  q({
    id: 'e-plate-max',
    key: 'plateMaxKg',
    category: 'equipment',
    answer: 'number',
    range: { min: 20, max: 300, unit: 'kg' },
    eligible: has('answers.equipmentList', 'barbell'),
    affects: ['equipment', 'progression'],
    priority: 48,
    infoGain: 5,
  }),
  q({
    id: 'e-rack',
    key: 'hasRack',
    category: 'equipment',
    answer: 'single',
    options: opts('none', 'stands', 'full_rack'),
    eligible: has('answers.equipmentList', 'barbell'),
    affects: ['equipment', 'safetyFlags', 'planConstraints'],
    safety: 'restrict',
    priority: 58,
    infoGain: 7,
  }),
  q({
    id: 'e-bench-kind',
    key: 'benchKind',
    category: 'equipment',
    answer: 'single',
    options: opts('none', 'flat', 'adjustable'),
    eligible: all(atHome, has('answers.equipmentList', 'bench')),
    affects: ['equipment', 'planConstraints'],
    priority: 44,
    infoGain: 5,
  }),
  q({
    id: 'e-bodyweight-only-confirm',
    key: 'bodyweightOnly',
    category: 'equipment',
    answer: 'boolean',
    eligible: hasNone('answers.equipmentList', ['dumbbell', 'barbell', 'machine', 'cable']),
    affects: ['equipment', 'trainingStyle', 'planConstraints'],
    priority: 62,
    infoGain: 7,
    followUps: [{ when: eq('answers.bodyweightOnly', true), ask: ['e-pullup-bar'] }],
  }),
  q({
    id: 'e-pullup-bar',
    key: 'hasPullupBar',
    category: 'equipment',
    answer: 'boolean',
    eligible: any(eq('answers.bodyweightOnly', true), all(atHome, hasNone('answers.equipmentList', ['machine', 'cable']))),
    affects: ['equipment', 'planConstraints'],
    priority: 52,
    infoGain: 6,
  }),
  q({
    id: 'e-space',
    key: 'trainingSpace',
    category: 'equipment',
    answer: 'single',
    options: opts('tiny', 'room', 'garage', 'outdoor'),
    eligible: atHome,
    affects: ['equipment', 'planConstraints'],
    priority: 46,
    infoGain: 5,
  }),
  q({
    id: 'e-noise-limit',
    key: 'noiseLimit',
    category: 'equipment',
    answer: 'boolean',
    eligible: oneOf('answers.trainingSpace', ['tiny', 'room']),
    affects: ['safetyFlags', 'planConstraints'],
    priority: 30,
    infoGain: 4,
  }),
  q({
    id: 'e-cardio-machines',
    key: 'cardioMachines',
    category: 'equipment',
    answer: 'multi',
    options: opts('none', 'treadmill', 'bike', 'elliptical', 'rower', 'stairs'),
    affects: ['cardio', 'planConstraints'],
    priority: 40,
    infoGain: 5,
  }),
  q({
    id: 'e-bands-only-detail',
    key: 'bandStrength',
    category: 'equipment',
    answer: 'single',
    options: opts('light', 'mixed', 'heavy'),
    eligible: all(has('answers.equipmentList', 'band'), hasNone('answers.equipmentList', ['barbell', 'machine'])),
    affects: ['equipment', 'progression'],
    priority: 32,
    infoGain: 4,
  }),
  q({
    id: 'e-travel-fallback',
    key: 'travelFallback',
    category: 'equipment',
    answer: 'single',
    options: opts('hotel_gym', 'bodyweight', 'bands', 'skip_training'),
    eligible: oneOf('answers.travelFrequency', ['monthly', 'weekly']),
    affects: ['equipment', 'planConstraints'],
    priority: 34,
    infoGain: 4,
  }),
  q({
    id: 'e-machine-access',
    key: 'machineAccess',
    category: 'equipment',
    answer: 'single',
    options: opts('none', 'few', 'most', 'all'),
    eligible: all(oneOf('answers.place', ['gym', 'mixed']), ne('answers.gymType', 'full')),
    affects: ['equipment', 'trainingStyle'],
    priority: 42,
    infoGain: 5,
  }),
  q({
    id: 'e-spotter',
    key: 'hasSpotter',
    category: 'equipment',
    answer: 'boolean',
    eligible: all(has('answers.equipmentList', 'barbell'), not(eq('answers.hasRack', 'full_rack'))),
    affects: ['safetyFlags', 'planConstraints'],
    safety: 'restrict',
    priority: 44,
    infoGain: 5,
  }),
  q({
    id: 'e-equipment-confidence',
    key: 'equipmentConfidence',
    category: 'equipment',
    answer: 'single',
    options: opts('lost', 'basics', 'confident'),
    eligible: all(oneOf('answers.place', ['gym', 'mixed']), answered('answers.selfLevel')),
    affects: ['experience', 'planConstraints'],
    priority: 36,
    infoGain: 5,
  }),
  q({
    id: 'e-weather-dependency',
    key: 'weatherDependency',
    category: 'equipment',
    answer: 'boolean',
    eligible: hasAny('answers.equipmentList', ['bodyweight']),
    affects: ['planConstraints'],
    priority: 20,
    infoGain: 3,
  }),
]
