// البنك — التفضيلات والتعافي ونمط الحياة.
//
// التفضيل ليس ترفًا: تمرين يكرهه المستخدم تمرين لن يُنفَّذ، والخطة التي تتجاهل
// ذلك تُقاس ممتازة وتُترك في الأسبوع الثاني. لذلك `p-disliked` و`p-preferred`
// يدخلان **الترتيب** لا الاستبعاد الصارم (الاستبعاد الصارم لـ`l-cannot-perform`
// وحده): الكراهية تُخفض الرتبة، والعجز يمنع.

import { q, opts } from './define'
import { all, any, eq, gte, oneOf, ne, has } from '../rules'
import type { QuestionDef } from '../types'

export const PREFERENCE_QUESTIONS: QuestionDef[] = [
  // ═══════════════════ التفضيلات ═══════════════════
  q({
    id: 'p-style',
    key: 'trainingStyle',
    category: 'preferences',
    answer: 'single',
    options: opts('machines', 'free_weights', 'mixed', 'bodyweight'),
    affects: ['trainingStyle', 'planConstraints'],
    priority: 74,
    required: true,
    skippable: false,
    infoGain: 8,
  }),
  q({
    id: 'p-compound-bias',
    key: 'compoundBias',
    category: 'preferences',
    answer: 'single',
    options: opts('compound', 'balanced', 'isolation'),
    eligible: ne('derived.experienceClass', 'complete_beginner'),
    affects: ['planConstraints', 'volume'],
    priority: 50,
    infoGain: 6,
  }),
  q({
    id: 'p-disliked',
    key: 'dislikedExercises',
    category: 'preferences',
    answer: 'exercises',
    affects: ['excludedExercises', 'planConstraints'],
    priority: 56,
    infoGain: 7,
  }),
  q({
    id: 'p-preferred',
    key: 'preferredExercises',
    category: 'preferences',
    answer: 'exercises',
    eligible: ne('derived.experienceClass', 'complete_beginner'),
    affects: ['preferredExercises', 'planConstraints'],
    priority: 48,
    infoGain: 6,
  }),
  q({
    id: 'p-variety',
    key: 'varietyPref',
    category: 'preferences',
    answer: 'single',
    options: opts('same', 'some', 'lots'),
    affects: ['planConstraints', 'progression'],
    priority: 44,
    infoGain: 5,
  }),
  q({
    id: 'p-cardio-type',
    key: 'cardioType',
    category: 'preferences',
    answer: 'multi',
    options: opts('walk', 'run', 'bike', 'row', 'swim', 'stairs', 'sport', 'hiit'),
    eligible: oneOf('answers.cardioWilling', ['little', 'yes', 'love_it']),
    affects: ['cardio', 'planConstraints'],
    priority: 46,
    infoGain: 6,
  }),
  q({
    id: 'p-cardio-timing',
    key: 'cardioTiming',
    category: 'preferences',
    answer: 'single',
    options: opts('after_lifting', 'separate_day', 'before', 'no_pref'),
    eligible: oneOf('answers.cardioWilling', ['yes', 'love_it']),
    affects: ['cardio', 'planConstraints', 'split'],
    priority: 38,
    infoGain: 5,
  }),
  q({
    id: 'p-superset-tolerance',
    key: 'supersetTolerance',
    category: 'preferences',
    answer: 'single',
    options: opts('no', 'ok', 'prefer'),
    eligible: oneOf('answers.sessionMinutes', ['20', '30', '45']),
    affects: ['planConstraints'],
    priority: 40,
    infoGain: 5,
  }),
  q({
    id: 'p-rest-preference',
    key: 'restPreference',
    category: 'preferences',
    answer: 'single',
    options: opts('short', 'moderate', 'long', 'auto'),
    eligible: ne('derived.experienceClass', 'complete_beginner'),
    affects: ['planConstraints'],
    priority: 36,
    infoGain: 5,
  }),
  q({
    id: 'p-music-cue-pref',
    key: 'coachingDensity',
    category: 'preferences',
    answer: 'single',
    options: opts('minimal', 'normal', 'detailed'),
    affects: ['controlLevel', 'planConstraints'],
    priority: 30,
    infoGain: 4,
  }),
  q({
    id: 'p-solo-or-partner',
    key: 'trainsWith',
    category: 'preferences',
    answer: 'single',
    options: opts('solo', 'partner', 'group'),
    affects: ['planConstraints'],
    priority: 22,
    infoGain: 3,
  }),
  q({
    id: 'p-mirror-avoid',
    key: 'crowdComfort',
    category: 'preferences',
    answer: 'single',
    options: opts('fine', 'prefer_quiet', 'avoid_busy'),
    eligible: oneOf('answers.place', ['gym', 'mixed']),
    affects: ['planConstraints', 'trainingStyle'],
    priority: 26,
    infoGain: 4,
  }),
  q({
    id: 'p-machine-vs-free-reason',
    key: 'styleReason',
    category: 'preferences',
    answer: 'single',
    options: opts('safety', 'simplicity', 'results', 'enjoyment'),
    eligible: oneOf('answers.trainingStyle', ['machines', 'free_weights']),
    affects: ['planConstraints', 'controlLevel'],
    priority: 28,
    infoGain: 4,
  }),
  q({
    id: 'p-session-structure',
    key: 'sessionStructure',
    category: 'preferences',
    answer: 'single',
    options: opts('fixed_order', 'flexible_order'),
    eligible: ne('derived.experienceClass', 'complete_beginner'),
    affects: ['planConstraints'],
    priority: 24,
    infoGain: 3,
  }),
  q({
    id: 'p-substitution-openness',
    key: 'substitutionOpenness',
    category: 'preferences',
    answer: 'single',
    options: opts('never', 'when_busy', 'always_ok'),
    affects: ['planConstraints'],
    priority: 34,
    infoGain: 5,
  }),
  q({
    id: 'p-warmup-time',
    key: 'warmupTime',
    category: 'preferences',
    answer: 'single',
    options: opts('none', 'short', 'full'),
    affects: ['planConstraints', 'sessionMinutes'],
    priority: 32,
    infoGain: 4,
  }),
  q({
    id: 'p-stretch-time',
    key: 'stretchTime',
    category: 'preferences',
    answer: 'single',
    options: opts('none', 'short', 'full'),
    eligible: ne('answers.mobilityGoal', 'no'),
    affects: ['planConstraints'],
    priority: 22,
    infoGain: 3,
  }),
  q({
    id: 'p-exercise-complexity',
    key: 'complexityAppetite',
    category: 'preferences',
    answer: 'single',
    options: opts('simple', 'moderate', 'technical'),
    affects: ['planConstraints', 'trainingStyle'],
    priority: 42,
    infoGain: 6,
  }),
  q({
    id: 'p-unilateral',
    key: 'unilateralOpenness',
    category: 'preferences',
    answer: 'single',
    options: opts('avoid', 'ok', 'prefer'),
    eligible: any(eq('answers.balanceIssue', 'none'), ne('answers.hasInjury', 'current')),
    affects: ['planConstraints'],
    priority: 20,
    infoGain: 3,
  }),
  q({
    id: 'p-home-noise-style',
    key: 'quietStyle',
    category: 'preferences',
    answer: 'boolean',
    eligible: eq('answers.noiseLimit', true),
    affects: ['excludedExercises', 'planConstraints'],
    priority: 28,
    infoGain: 4,
  }),

  // ═══════════════════ التعافي ونمط الحياة ═══════════════════
  q({
    id: 'r-sleep-hours',
    key: 'sleepHours',
    category: 'recovery',
    answer: 'single',
    options: opts('lt5', 'h5_6', 'h6_7', 'h7_8', 'gt8'),
    affects: ['recovery', 'volume', 'planConstraints'],
    priority: 68,
    infoGain: 8,
  }),
  q({
    id: 'r-sleep-quality',
    key: 'sleepQuality',
    category: 'recovery',
    answer: 'single',
    options: opts('poor', 'fair', 'good'),
    eligible: oneOf('answers.sleepHours', ['lt5', 'h5_6', 'h6_7']),
    affects: ['recovery', 'volume'],
    priority: 54,
    infoGain: 6,
  }),
  q({
    id: 'r-stress',
    key: 'stressLevel',
    category: 'recovery',
    answer: 'single',
    options: opts('low', 'moderate', 'high'),
    affects: ['recovery', 'volume', 'intensity'],
    priority: 60,
    infoGain: 7,
  }),
  q({
    id: 'r-work-type',
    key: 'workType',
    category: 'recovery',
    answer: 'single',
    options: opts('desk', 'mixed', 'standing', 'physical', 'shift'),
    affects: ['recovery', 'planConstraints', 'cardio'],
    priority: 58,
    infoGain: 7,
  }),
  q({
    id: 'r-daily-steps',
    key: 'dailySteps',
    category: 'recovery',
    answer: 'single',
    options: opts('lt3k', 'k3_6', 'k6_10', 'gt10k', 'unknown'),
    affects: ['cardio', 'recovery', 'planConstraints'],
    priority: 56,
    infoGain: 7,
  }),
  q({
    id: 'r-soreness-history',
    key: 'sorenessHistory',
    category: 'recovery',
    answer: 'single',
    options: opts('rare', 'normal', 'lingering'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['recovery', 'volume'],
    priority: 48,
    infoGain: 6,
  }),
  q({
    id: 'r-fatigue-after-session',
    key: 'fatigueAfter',
    category: 'recovery',
    answer: 'single',
    options: opts('energised', 'normal', 'wiped'),
    eligible: ne('answers.trainedBefore', 'never'),
    affects: ['recovery', 'volume', 'intensity'],
    priority: 46,
    infoGain: 6,
  }),
  q({
    id: 'r-other-sport-now',
    key: 'otherSportNow',
    category: 'recovery',
    answer: 'single',
    options: opts('none', 'light', 'regular', 'competitive'),
    affects: ['recovery', 'volume', 'cardio', 'planConstraints'],
    priority: 52,
    infoGain: 7,
    followUps: [{ when: oneOf('answers.otherSportNow', ['regular', 'competitive']), ask: ['r-sport-days'] }],
  }),
  q({
    id: 'r-sport-days',
    key: 'sportDaysPerWeek',
    category: 'recovery',
    answer: 'single',
    options: opts('1', '2', '3', '4plus'),
    eligible: oneOf('answers.otherSportNow', ['regular', 'competitive']),
    affects: ['volume', 'daysPerWeek', 'planConstraints'],
    priority: 50,
    infoGain: 7,
  }),
  q({
    id: 'r-hydration',
    key: 'hydrationHabit',
    category: 'recovery',
    answer: 'single',
    options: opts('low', 'ok', 'good'),
    affects: ['planConstraints'],
    priority: 20,
    infoGain: 3,
  }),
  q({
    id: 'r-meals-per-day',
    key: 'mealsPerDay',
    category: 'recovery',
    answer: 'single',
    options: opts('1_2', '3', '4', '5plus'),
    eligible: ne('answers.nutritionInterest', 'skip'),
    affects: ['planConstraints'],
    priority: 34,
    infoGain: 4,
  }),
  q({
    id: 'r-appetite',
    key: 'appetite',
    category: 'recovery',
    answer: 'single',
    options: opts('low', 'normal', 'high'),
    eligible: ne('answers.nutritionInterest', 'skip'),
    affects: ['planConstraints'],
    priority: 26,
    infoGain: 4,
  }),
  q({
    id: 'r-caffeine',
    key: 'caffeineTiming',
    category: 'recovery',
    answer: 'single',
    options: opts('none', 'morning', 'all_day', 'late'),
    eligible: oneOf('answers.sleepQuality', ['poor', 'fair']),
    affects: ['recovery'],
    priority: 18,
    infoGain: 3,
  }),
  q({
    id: 'r-recovery-selfrating',
    key: 'recoverySelfRating',
    category: 'recovery',
    answer: 'slider',
    range: { min: 1, max: 5, step: 1 },
    affects: ['recovery', 'volume'],
    priority: 44,
    infoGain: 6,
  }),
  q({
    id: 'r-deload-history',
    key: 'deloadHistory',
    category: 'recovery',
    answer: 'single',
    options: opts('never', 'sometimes', 'planned'),
    eligible: oneOf('derived.experienceClass', ['intermediate', 'advanced']),
    affects: ['progression', 'volume'],
    priority: 32,
    infoGain: 5,
  }),
  q({
    id: 'r-injury-prone',
    key: 'injuryProne',
    category: 'recovery',
    answer: 'boolean',
    eligible: all(gte('answers.age', 30), ne('answers.trainedBefore', 'never')),
    affects: ['recovery', 'volume', 'safetyFlags'],
    safety: 'restrict',
    priority: 40,
    infoGain: 5,
  }),
  q({
    id: 'r-sitting-hours',
    key: 'sittingHours',
    category: 'recovery',
    answer: 'single',
    options: opts('lt4', 'h4_8', 'gt8'),
    eligible: has('answers.workType', 'desk'),
    affects: ['musclePriorities', 'planConstraints'],
    priority: 24,
    infoGain: 4,
  }),
]
